# Generated by Django 3.2.2 on 2021-05-25 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210526_0114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registrationn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('city', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
