# Generated by Django 3.2.2 on 2021-05-25 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210526_0245'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registrationn',
            new_name='Registration',
        ),
    ]
